### ISSUE TITLE
IsJson helper method

### ISSUE THREAD

**Issue by nadar** [yiisoft/json#6]
We have a very convenient method to check whether an input is already a json value:

https://github.com/luyadev/luya/blob/master/core/helpers/Json.php#L19-L49

If this sounds interesting for this package, i would make a PR.

**Comment by samdark** [comment]
Thanks for idea but I don't think it fits.

1. Seems it's not checking for valid JSON but is doing something else. It will return `false` for `"test"` or `42` that is valid JSON.
2. If we consider these valid variants, there's no profit in having this method since we'll do decode in order to know if JSON is valid.
3. We have to catch `\JsonException` anyway when decoding.

**Comment by nadar** [comment]
What your are talking about is this i assume: https://stackoverflow.com/a/7487892/4611030

But in 99% percent of the situations the method could help developers when dealing with JSON. So maybe make a good example how people can ensure that behavior with this package with try catch blocks.

**Comment by nadar** [comment]
(ps: maybe its also just my personal taste of what i expected from such a library: methods which helps me to find solutions for problems right at my fingertips...)

**Comment by samdark** [comment]
It is likely that I'm not getting the problem and how this helper method solves it.
